// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVndeT-KqTxEH_91XWgZ0FplxWEUhFeSA',
    appId: '1:418740359006:web:2fd25f81bd86c015b189cf',
    messagingSenderId: '418740359006',
    projectId: 'wechat-3fe3f',
    authDomain: 'wechat-3fe3f.firebaseapp.com',
    storageBucket: 'wechat-3fe3f.appspot.com',
    measurementId: 'G-881SGWWRR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrknVWt1IcIgtnXUc64Z-mujP5RuJtQnk',
    appId: '1:418740359006:android:b30c2ea157c66b62b189cf',
    messagingSenderId: '418740359006',
    projectId: 'wechat-3fe3f',
    storageBucket: 'wechat-3fe3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1RFcWnolLQWJE9iReOk15f0aBWFQjL0',
    appId: '1:418740359006:ios:fb5c2db0560adc64b189cf',
    messagingSenderId: '418740359006',
    projectId: 'wechat-3fe3f',
    storageBucket: 'wechat-3fe3f.appspot.com',
    androidClientId: '418740359006-52s7o8gmobm945c00r1k65e136u006nf.apps.googleusercontent.com',
    iosClientId: '418740359006-mffj1eqmupd68kh9tgn34afg7rl9paak.apps.googleusercontent.com',
    iosBundleId: 'com.lambert.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1RFcWnolLQWJE9iReOk15f0aBWFQjL0',
    appId: '1:418740359006:ios:c15ab52d461d628db189cf',
    messagingSenderId: '418740359006',
    projectId: 'wechat-3fe3f',
    storageBucket: 'wechat-3fe3f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVndeT-KqTxEH_91XWgZ0FplxWEUhFeSA',
    appId: '1:418740359006:web:1f38647ef7190b03b189cf',
    messagingSenderId: '418740359006',
    projectId: 'wechat-3fe3f',
    authDomain: 'wechat-3fe3f.firebaseapp.com',
    storageBucket: 'wechat-3fe3f.appspot.com',
    measurementId: 'G-LLVGKV07PD',
  );
}